server:
  port: 8080

spring:
  application:
    name: api-gateway

cloud:
  gateway:
    routes:
      - id: auth-service
        uri: lb://api-gateway:0f9ff430b485d7b273968196826fac04
        predicates:
          - Path=/token
        filters:
          - RewritePath=/token, /api/v1/auth/token

      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/auth/**
          - Path=/users/**

      - id: event-service
        uri: lb://event-service
        predicates:
          - Path=/events/**

      - id: ticket-service
        uri: lb://ticket-service
        predicates:
          - Path=/tickets/**

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  secret-key: ticketqube