spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888/api-gateway/default" # Correct format for importing from Config Server
  cloud:
    config:
      uri: http://localhost:8888/api-gateway/default

server:
  port: 8080

cloud:
  gateway:
    routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/users/**
      - id: event-service
        uri: lb://event-service
        predicates:
          - Path=/events/**
      - id: ticket-service
        uri: lb://ticket-service
        predicates:
          - Path=/tickets/**



management:
  endpoints:
    web:
      exposure:
        include: "*"