server:
  port: 8080

spring:
  application:
    name: api-gateway

cloud:
  gateway:
    routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/users/**
      - id: event-service
        uri: lb://event-service
        predicates:
          - Path=/events/**
      - id: ticket-service
        uri: lb://ticket-service
        predicates:
          - Path=/tickets/**



management:
  endpoints:
    web:
      exposure:
        include: "*"