server:
  port: 8082  # Assign a dynamic port

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://auth-service-db:5432/db
    username: admin_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  secret-key: b6c70455e19a0180e5b1abd97cab4041be7a6131ac436170ed7b88947b9baa09

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
