server:
  port: 0  # Assign a dynamic port

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
